### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "886cfd53e2e3461bb70a37cada3bc511",
  "accountNumber": "1000000002",
  "amount" : 100
}

### query transaction
GET http://localhost:8080/transaction/47eac269922541a99e5618fc9a2f29b6